### ISSUE TITLE
撤回消息不可用

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker-nt-cc-yunzai-ws#7]
最终节点的报错是IndexError: list index out of range

**Comment by SlightDust** [comment]
[2023-10-14 02:10:35,731 recall] ERROR: <class 'IndexError'> occured when recall handling message 1424026059.
[2023-10-14 02:10:35,731 recall] ERROR: list index out of range
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/qqbot/HoshinoBot/hoshino/modules/groupmanager/recall.py", line 13, in recall
    mid = re.findall(p1, ev.raw_message)[0]
IndexError: list index out of range

**Comment by SlightDust** [comment]
原因分析：  
对接gocq时没有移除reply消息中自带的at，匹配规则为：`\[CQ:reply,id=(.*?)\]\[CQ:`  
对接yunzai后接收消息为`[2023-10-14 02:12:28,973 nonebot] INFO: Self: 2471737329, Message -258743465 from 1085289815@[群:276196898]: '[CQ:reply,id=717850793]撤回'`  
可见yunzai默认移除了reply消息中自带的at

**Comment by SlightDust** [comment]
原因分析：  
对接gocq时没有移除reply消息中自带的at，匹配规则为：`\[CQ:reply,id=(.*?)\]\[CQ:`  
对接yunzai后接收消息为`[2023-10-14 02:12:28,973 nonebot] INFO: Self: xxxxxxxx, Message -258743465 from xxxxxxxxx@[群:xxxxxxxxxx]: '[CQ:reply,id=717850793]撤回'`  
可见yunzai默认移除了reply消息中自带的at

**Comment by SlightDust** [comment]
切回gocq可用，close
