### ISSUE TITLE
hoshino控制台持续报错KeyError: 'coolq_directory'

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker-nt-cc-yunzai-ws#8]
hoshino-print-qrcode报错

**Comment by SlightDust** [comment]
`[2023-10-14 02:18:46,868 pqrcode] ERROR: <class 'KeyError'> occured when on_input_chara_name handling message 210568497.
[2023-10-14 02:18:46,868 pqrcode] ERROR: 'coolq_directory'
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/root/qqbot/HoshinoBot/hoshino/modules/hoshino-print-qrcode/main.py", line 130, in on_input_chara_name
    cache["coolq_directory"] = Path(cq_info["coolq_directory"])
KeyError: 'coolq_directory'`

**Comment by SlightDust** [comment]
原因分析：
1. gocq实现的一个API [get_version_info](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%89%88%E6%9C%AC%E4%BF%A1%E6%81%AF)，原插件调用这个API最终要取`"coolq_directory":"/root/qqbot/mirai"`字段，即gocq根目录
2. 继续往下，原插件还调用了`get_login_info` API，目的是取得`nickname`和`user_id`

先把这3个值都在加载插件时写死试试

**Comment by SlightDust** [comment]
收到普通文字消息不报错。收到图片报错

> [2023-10-14 02:41:17,285 pqrcode] ERROR: <class 'TypeError'> occured when on_input_chara_name handling message 2123004163.
[2023-10-14 02:41:17,285 pqrcode] ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/root/qqbot/HoshinoBot/hoshino/modules/hoshino-print-qrcode/main.py", line 136, in on_input_chara_name
    async for data in read_img(ev.message):
  File "/root/qqbot/HoshinoBot/hoshino/modules/hoshino-print-qrcode/main.py", line 98, in read_img
    file = cache["coolq_directory"] / cq_img_info["file"]
TypeError: 'NoneType' object is not subscriptable

#1 get_image接口的问题吧……

**Comment by SlightDust** [comment]
>     for img_data in imgs:
>         print(img_data)
>         cq_img_info = await bot.get_image(file=img_data["file"])
>         print(cq_img_info)

`img_data`打印为`{'file': '44630e33d09898e0xxxxxxxxxx', 'subType': 0, 'url': 'https://gchat.qpic.cn/gchatpic_new/0/0-0-44630E33Dxxxxxxxxxxxxxx'}`  
`cq_img_info`打印为`None`

**Comment by SlightDust** [comment]
解决方案：重写read_img函数，不判断文件是否以.image结尾，写死为从img_data中取url数据。
``` python
async def read_img(message: Message):
    aio_cor = []
    imgs = await process_img(message)
    for img_data in imgs:
        aio_cor.append(aio_image(img_data["url"], Path(img_data["file"]).stem))
    for raw in await asyncio.gather(*aio_cor):
        for data in decode(raw):
            yield data
```
不保证再切换回gocq还能不能用  
而且现在这种方案是因为除了NTQQ外，原来的gocq还挂着，所以才能从目录中取到图片

**Comment by SlightDust** [comment]
trss-yunzai这边会直接给出图片链接
```
[TRSSYz][02:57:54.824][INFO] [2471737329] 群消息：[域宝2测试(xxxxxxx), 轻尘喵(xxxxxxxxx)] [图片:
https://gchat.qpic.cn/gchatpic_new/0/0-0-40E6DBAB6CBxxxxxxxxxxxxxx]
```

**Comment by SlightDust** [comment]
切回gocq可用，close
